Feature Extraction

Bag-of-Words

In [2]:
# Bag of words model  (BOW)
# represent all the bags in a matrix of size (number of bags, number of words in the vocabulary) 
# each row is a bag and each column is a word in the vocabulary
# the value in each cell is the number of times the word appears in the bag
# the vocabulary is the set of all the words in the corpus
# the corpus is the set of all the bags
# the number of bags is the number of documents in the corpus
# the number of words in the vocabulary is the number of unique words in the corpus


# TF-IDF model
# Word2Vec model


In [3]:
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from preprocess import Preprocess 
preprocess = Preprocess()

Emojis:  True
Lemmatizor:  camel


In [2]:
# nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emada\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
# read the data
t = pd.read_csv('./Dataset/train.csv')
X = t['text']

In [5]:
# do the preprocessing
X = X.apply(preprocess.do_all)

In [9]:
print(X[0])
print(X[1])

['بِيل', 'غيتس', 'تَلَقَّى', 'لَقاح', 'مِن', 'غَيْر', 'تَصْوِير', 'إِبْرَة', 'وَ', 'السيرنجه', 'وَ', 'دَواء', 'وَ', 'لابَس', 'بُولُو', 'صَيْفِيّ', 'فِي', 'عِزّ', 'شِتاء', 'وَ', 'قال', 'أَنَّ', 'أَحَد', 'مَزِيَّة', 'عُمَر', 'ال', 'عام', 'هِيَ', 'أَنَّ', 'مُؤَهَّل', 'حُصُول', 'عَلَى', 'لَقاح', 'عَنَى', 'ٱِحْتاج', 'لَقاح', 'لَو', 'عُمْر', 'أَصْغَر', 'مِن', '<NUM>', '<NUM>', '<NUM>', '<thinking_face>', '<LINK>', 'كوفيد', 'كوفيد', 'كوفيد']
['وَزِير', 'صِحَّة', 'لَحَد', 'يَوْم', 'تَحْدِيد', 'هَلّا', 'بمؤتمروا', 'صُحُفِيّ', 'عِنْد', 'مُشْكِلَة', 'مَعا', 'بَسّ', 'آن', 'بفايزر', 'هُوَ', 'لَقاح', 'وَحِيد', 'أَمْن', 'عالَم', 'حُبَيْبِيّ', 'هاي', 'فِي', 'أَفاق', 'واضِح', 'عَفْو', 'عَنَى', 'مَشّ', 'آن', 'مَجْبُور', 'فِي', 'قادِر', 'أَجْبَر', 'دَوْلَة', 'مارِق', 'دَفَع', 'مَصارِيّ', 'أَجاب', 'لَقاح', 'تَأَنِّي', 'يلا', 'أَيّ', '<LF>', '<LF>', '<LF>', '<LF>']


In [10]:
# count vectorizer function takes sentences as input 
# convert it into matrix representation 
# where each cell will be filled by the frequency of each vocab
# vectorizer = CountVectorizer()
# bow_model = vectorizer.fit_transform(X)

AttributeError: 'list' object has no attribute 'lower'

In [ ]:
# print(bow_model.toarray())

[[0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# transform the matrx into pandas dataframe 
# to set the column names as actual vocab words which are our features
# df_bow = pd.DataFrame(bow_model.toarray(), columns = vectorizer.get_feature_names())
# df_bow

1780  65  9kte81z1jk  co  https  lf  nnatra5bpb  qbustq1kpy  qqkffunwbn  \
0     0   2           0   1      1   0           0           0           1   
1     0   0           0   0      0   4           0           0           0   
2     0   0           0   0      0   2           0           0           0   
3     0   0           0   1      1   0           0           1           0   
4     0   0           0   0      0   1           0           0           0   
5     0   0           0   1      1   1           1           0           0   
6     0   0           0   0      0   0           0           0           0   
7     0   0           0   0      0   2           0           0           0   
8     1   0           1   1      1   4           0           0           0   
9     0   0           0   0      0   1           0           0           0   

   user  ...  يشتم  يطلع  يعنى  يعني  يقول  يكونو  يلا  يلي  يوصل  ١٦  
0     0  ...     0     0     1     0     1      0    0    0     0   0  
1     0  ...     0     0     0     1     0      0    1    0     0   0  
2     0  ...     0     0     0     0     0      1    0    0     1   0  
3     0  ...     0     0     0     0     0      0    0    0     0   0  
4     1  ...     1     0     0     0     0      0    0    0     0   0  
5     0  ...     0     0     0     0     0      0    0    0     0   0  
6     0  ...     0     0     0     0     0      0    0    1     0   1  
7     0  ...     0     0     0     0     0      0    0    0     0   0  
8     1  ...     0     0     0     0     0      0    0    0     0   0  
9     0  ...     0     1     0     0     0      0    0    0     0   0  

[10 rows x 227 columns]

In [ ]:
#show all features (unique words)
# print(vectorizer.get_feature_names())


['1780', '65', '9kte81z1jk', 'co', 'https', 'lf', 'nnatra5bpb', 'qbustq1kpy', 'qqkffunwbn', 'user', 'ألفي', 'أميركا', 'أنقرة', 'أوكسفام', 'أول', 'إحدى', 'إسلامية', 'إنوا', 'اتابع', 'اد', 'اذا', 'اشترى', 'اصغر', 'اعلامية', 'ال', 'الآمن', 'الأجدر', 'الإنفوغراف', 'الابرة', 'الاخبار', 'التوزيع', 'التي', 'الثلاجة', 'الخطأ', 'الخليجية', 'الدواء', 'الدول', 'الدولة', 'الدين', 'السيرنجة', 'الشتاء', 'الصحة', 'الصحفي', 'الصيني', 'الضريبة', 'العادل', 'اللقاح', 'المارقة', 'المسؤولية', 'النظافة', 'الوحيد', 'الى', 'اليوم', 'امريكي', 'ان', 'انت', 'انه', 'انوا', 'اول', 'بالعاصمة', 'بالعالم', 'باي', 'بدعم', 'بدها', 'بدهم', 'بس', 'بعتقد', 'بعض', 'بفايزر', 'بفضل', 'بكرا', 'بكل', 'بمؤتمروا', 'بنذكر', 'بها', 'بوسطن', 'بولو', 'بيل', 'تاني', 'تجبر', 'تجيب', 'تحت', 'تدعي', 'تدفع', 'تركيا', 'تستحي', 'تصوير', 'تصير', 'تهكير', 'توقيفه', 'ثرواتهم', 'جاء', 'جرعة', 'حبيبي', 'حسابك', 'حضرتك', 'حفظت', 'دبي', 'دعبول', 'دعبول_دومه_مسحول', 'دولة', 'رح', 'رضت', 'سنة', 'شئت', 'شلنا', 'شي', 'صيفي', 'طريق', 'طلة', 'عاصي_الحل

Word2Vec

In [23]:
# Word2vec is trained to predict the nearest word belongs to the context
# e.g. to tell if "milk" is a likely word given the "The cat was drinking..."
import gensim
from gensim.models import Word2Vec
import numpy as np

In [30]:
# Create CBOW (Continuous Bag of Words) model 
model_cbow = Word2Vec(X, min_count = 1, vector_size = 300, window = 5) 
# applied on the preprocessed data X
# print(model_cbow)
# words_cbow = list(model_cbow.wv.index_to_key)
# print(words_cbow[0:5])

# print the vector of a word
# print(model_cbow.wv.get_vector('مِن'))
# print(len(model_cbow.wv[model_cbow.wv.index_to_key]))

In [31]:
# create skip-gram model (SG) 
model_sg = Word2Vec(X, min_count = 1, vector_size = 300, window = 5, sg=2) 
# applied on the preprocessed data X
# print(model_sg)
# words_sg = list(model_sg.wv.index_to_key)
# print(words_sg[0:5])

# print the vector of a word
# print(model_sg.wv['مِن'])

# model_sg.wv['word']: has the vector of the word

In [25]:
# don't apply mean for the LSTM/RNN models
def get_mean_vector(word2vec_model, words):
    # remove out-of-vocabulary words
    words = [word for word in words if word in word2vec_model.wv.index_to_key]
    if len(words) >= 1:
        return np.mean(word2vec_model.wv[words], axis=0)
    else:
        return []

In [ ]:
# get the vector of the first sentence
get_mean_vector(model_cbow, X[0])

In [ ]:
get_mean_vector(model_sg, X[0])

In [32]:
# append the vectors of all sentences to a list
vectors_cbow = []
vectors_sg = []
# get the vector of all sentences 
for sentence in X:
    vec = get_mean_vector(model_cbow, sentence)
    if len(vec) > 0:
        vectors_cbow.append(vec)

for sentence in X:
    vec = get_mean_vector(model_sg, sentence)
    if len(vec) > 0:
        vectors_sg.append(vec)
